# Generated by Django 5.0.3 on 2024-04-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alumni_eleve_alter_comment_id_alter_follower_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
