# Generated by Django 5.0.3 on 2024-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alumni_eleve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Alumni', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='n', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='n', upload_to='covers/'),
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
