# Generated by Django 5.0.3 on 2024-04-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_alter_user_bio_alter_user_cover_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='user_group',
        ),
    ]
