# Generated by Django 5.0.3 on 2024-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_rename_user_type_user_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='cvs/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
