# Generated by Django 5.0.3 on 2024-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PFE', 'PFE'), ('Operateur', 'Stage Opérateur'), ('Academique', 'Stage Académique'), ('Mentorat', 'Mentorat')], max_length=20)),
            ],
        ),
    ]
