# Generated by Django 5.0.3 on 2024-05-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_user_ancienne_ecole_user_anne_de_cesure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ancienne_ecole',
        ),
        migrations.RemoveField(
            model_name='user',
            name='anne_de_cesure',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_de_graduation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entreprise_visite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='majeur',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobilite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numero_de_telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='poste_occupee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secteurs_d_activites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_pfe',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=22, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
