# Generated by Django 5.0.3 on 2024-06-18 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_user_elective_user_graduation_date_user_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='elective',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option',
        ),
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, choices=[('Industrie', 'Industrie'), ('Aide à la Décision', 'Aide à la Décision'), ('Énergie', 'Énergie'), ('Matériau', 'Matériau')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
