# Generated by Django 5.0.3 on 2024-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_remove_user_elective_remove_user_option_user_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competence_concevoir_rechercher',
            field=models.CharField(blank=True, choices=[('Applications de la physique statistique aux SHS', 'Applications de la physique statistique aux SHS'), ('Introduction à la cyber Sécurité', 'Introduction à la cyber Sécurité'), ('Physique théorique', 'Physique théorique'), ('Gestion des risques', 'Gestion des risques'), ("Traitement d'images et multimédias", "Traitement d'images et multimédias"), ('Processus Stochastiques', 'Processus Stochastiques')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='competence_developper_innover',
            field=models.CharField(blank=True, choices=[('Logiciel industriel ABAQUS', 'Logiciel industriel ABAQUS'), ('Durabilité environnementale et justice sociale', 'Durabilité environnementale et justice sociale'), ('Réseaux Telecoms', 'Réseaux Telecoms'), ('La ville de demain : initiation à une démarche responsable et durable', 'La ville de demain : initiation à une démarche responsable et durable'), ('Nouvelles technologies pour la mobilité terrestre', 'Nouvelles technologies pour la mobilité terrestre'), ('Facteurs Humains', 'Facteurs Humains')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='competence_produire_promouvoir_vendre',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Fondamentaux de la Finance du Marché', 'Fondamentaux de la Finance du Marché'), ("Finance d'entreprise", "Finance d'entreprise"), ("Stratégie d'entreprise", "Stratégie d'entreprise"), ('Entreprenariat social et défis socio-économiques en Afrique : stratégies pour un développement durable', 'Entreprenariat social et défis socio-économiques en Afrique : stratégies pour un développement durable'), ("Introduction à l'analyse politique du monde contemporain", "Introduction à l'analyse politique du monde contemporain")], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='option',
            field=models.CharField(blank=True, choices=[('Génie Industriel', 'Génie Industriel'), ('Data Science et Digitalisation', 'Data Science et Digitalisation'), ('Énergie', 'Énergie')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, choices=[('Industrie 4.0', 'Industrie 4.0'), ('Ingénierie des Systèmes Complexes', 'Ingénierie des Systèmes Complexes'), ('Entreprendre en Afrique', 'Entreprendre en Afrique')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, choices=[('Aide à la Décision', 'Aide à la Décision'), ('Énergie', 'Énergie'), ('Matériau', 'Matériau'), ('Industrie', 'Industrie')], max_length=50, null=True),
        ),
    ]
