# Generated by Django 5.0.3 on 2024-06-19 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_user_competence_concevoir_rechercher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='competence_concevoir_rechercher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='competence_developper_innover',
        ),
        migrations.RemoveField(
            model_name='user',
            name='competence_produire_promouvoir_vendre',
        ),
        migrations.CreateModel(
            name='Electif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('concevoir_rechercher', 'Concevoir et Rechercher'), ('developper_innover', 'Développer et Innover'), ('produire_promouvoir_vendre', 'Produire, Promouvoir et Vendre')], max_length=50)),
                ('competence', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electifs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Elective',
        ),
    ]
