# Generated by Django 5.0.3 on 2024-06-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_remove_user_competence_concevoir_rechercher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='poste_occupe',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
    ]
