# Generated by Django 5.0.3 on 2024-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_poste_poste_occupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
